# Generated by Django 6.0.5 on 2026-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Может снимать с публикации")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано"), ("hidden", "Скрыто модератором")],
                default="draft",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
